### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zjedwin** [arnoldna/TomeRater#1]
Thanks for your submission. The points that I make below mostly concern small errors that effect complete correctness of some methods.
---
A minor comment. The methods `change_email` and `__repr__` should _print_ instead of _return_ the strings. 
---
Two comments on your `get_average_rating` implementation for the `User` class. First, let's consider the following snippet.
```python
  for key, value in self.books.items():
    if value is not None:
      sum_of_ratings.append(value)
  for value in sum_of_ratings:
    total += value
```
Here you can combine the two for loops into one:
```python
  for key, value in self.books.items():
    if value is not None:
      sum_of_ratings.append(value)
      total += value
```
From this we see that we don't need to make `sum_of_ratings` hold the values. It is enough for it to simply keep track of the number of values which are not `None`. Keeping the name the same, we can accomplish that like this
```python
sum_of_ratings = 0
...
  for key, value in self.books.items():
    if value is not None:
      sum_of_ratings += 1
      total += value
```
Now we can divide by these values directly. That brings me to my second comment. Let's look at the following line.
```python
  return round(total/sum_of_ratings, 1) # changed from "return round(total / len(sum_of_ratings), 1)"
```
One thing that you should check here is that `sum_of_ratings != 0` to avoid a division by zero error. It may be the case that _all_ ratings are in fact `None` in which case both `total` and `sum_of_ratings` will be zero.
---
The same comments I make for the `User` class's `get_average_rating` method also goes for the same method in the `Book` class.
---
Within the `print_catalog` and `print_user` methods, there's no need to place the print statement within brackets. You can simply write a usual for-in loop. That is,
```python
for Y in X:
  print(Y)
```
As written now, as a byproduct of using list comprehension to print the entries, you create a list of `None` values.
---
Notice that the methods, `most_read_book`, `highest_rated_book`, and `most_positive_user` have implementations which are copy/paste of one another with minor changes. Whenever you have a circumstance where a core functionality being performed is the same across many parts of your code, it is often a good idea to think of abstracting that core functionality out into a separate function. You can then call that function multiple times instead of copying code multiple times. The same can be said about `get_n_most_read_books` and `get_n_most_prolific_readers`.

**Comment by arnoldna** [comment]
Thank you for you quick feedback.

One of the areas I found that was challenging was dealing with printing. If we look at the following method.

`    def print_catalog(self):
        [print(Book.get_title(key)) for key in self.books.keys()]
        return`

Printing works appropriately. For some reason if I print your way then I don't get the actual title for one of the books but an object reference instead.

<TomeRater.Book object at 0x0000027F0B695128>

**Comment by zjedwin** [comment]
You get that when you write the following?
```python
def print_catalog(self):
    for key in self.books.keys():
        print(Book.get_title(key))
```
The example of
```python
for Y in X:
    print(Y)
```
was oversimplified and I realize now, misleading. I only mean that you can use something like that pattern instead of list comprehension to print.

**Comment by arnoldna** [comment]
Thank you. That makes sense now.
